global using static CommonBasicLibraries.BasicDataSettingsAndProcesses.BasicDataFunctions;
global using CommonBasicLibraries.CollectionClasses;
global using MediaHelpers.CoreLibrary.Video.TelevisionMiscClasses;
global using MediaHelpers.CoreLibrary.Video.DatabaseInterfaces.TVShows;
global using static CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions.Dates;
global using MediaHelpers.CoreLibrary.Video.DatabaseInterfaces.Movies;
global using CommonBasicLibraries.BasicDateTimeProcesses;
global using CommonBasicLibraries.BasicUIProcesses;
global using CommonBasicLibraries.DatabaseHelpers.ConditionClasses;
global using MediaHelpers.CoreLibrary.Music.DB.DataAccess;
global using MediaHelpers.CoreLibrary.Music.DB.Models;
global using MediaHelpers.CoreLibrary.Music.Helpers;
global using MediaHelpers.CoreLibrary.Music.TemporaryModels;
global using System.Data;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using CommonBasicLibraries.DatabaseHelpers.Extensions;
global using MediaHelpers.CoreLibrary.BasicInterfaces;
global using static CommonBasicLibraries.DatabaseHelpers.MiscClasses.StaticHelpers;
global using cs1 = CommonBasicLibraries.DatabaseHelpers.ConditionClasses.ConditionOperators;
global using cc1 = CommonBasicLibraries.BasicDataSettingsAndProcesses.SColorString;
global using MediaHelpers.CoreLibrary.Music.BasicRandomizer;
global using MediaHelpers.CoreLibrary.Music.PlayListCreaterClasses;
global using MediaHelpers.CoreLibrary.Music.DB.Helpers;
global using fs1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings;
global using static MediaHelpers.CoreLibrary.Music.BasicRandomizer.Globals;
global using static CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using CommonBasicLibraries.MediaHelpers.Models;
global using MediaHelpers.CoreLibrary.Video.Logic;
global using gg1 = CommonBasicLibraries.MediaHelpers.Helpers.MediaGlobalClass;
global using MediaHelpers.CoreLibrary.Video.Helpers;
global using Microsoft.AspNetCore.Components;
global using BasicBlazorLibrary.Components.AutoCompleteHelpers;
global using BasicBlazorLibrary.Components.Layouts;
global using MediaHelpers.CoreLibrary.Video.ViewModels;
global using BasicBlazorLibrary.Components.BaseClasses;
global using MediaHelpers.CoreLibrary.Video.RemoteControls;
global using MediaHelpers.CoreLibrary.Music.PlaySongsClasses;
global using MediaHelpers.CoreLibrary.Music.RemoteControls;
global using MediaHelpers.CoreLibrary.Music.ViewModels;
global using BasicBlazorLibrary.Components.InputNavigations;
global using MediaHelpers.CoreLibrary.Music.Components.Playlists;
global using ee1 = MediaHelpers.CoreLibrary.Video.TelevisionMiscClasses.Helpers;